# Generated by Django 4.1.2 on 2022-10-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciseinfo',
            name='page_and_exercise',
            field=models.CharField(max_length=100),
        ),
    ]
