# Generated by Django 4.1.2 on 2022-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cello', '0002_alter_book_date_alter_exerciseinfo_page_and_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinfo',
            name='page_and_exercise',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
