# Generated by Django 4.1.2 on 2022-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cello', '0004_subtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinfo',
            name='tags',
            field=models.ManyToManyField(db_table='cello_exercise', to='cello.tag'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
