# Generated by Django 4.1.2 on 2022-12-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cello', '0006_editexerciserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editexerciserequest',
            name='new_link',
        ),
        migrations.AddField(
            model_name='editexerciserequest',
            name='new_book_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cello.book'),
            preserve_default=False,
        ),
    ]
