# Generated by Django 4.1.2 on 2022-12-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cello', '0006_editexerciserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='editexerciserequest',
            name='new_link',
            field=models.CharField(default='null', max_length=2048),
            preserve_default=False,
        ),
    ]
